#!/usr/bin/env bash

IMPORTS=(
    LMG_DATA_FOLDER
    LMG_TASK_FOLDER
    LMG_TASK_RUNNER_FOLDER
    LMG_TASK_RUNNER_VERSION_FILENAME
    LMG_TASK_RUNNER_COMMAND_FILENAME
    LMG_TASK_SCRIPT_NAME_UP
    LMG_TASK_SCRIPT_NAME_DOWN
    LMG_TASK_INFO_NAME_UP
    LMG_TASK_INFO_NAME_DOWN
    LMG_TASK_INFO_VIEWER
    LMG_TASK_TYPE_FILENAME
    LMG_TASK_NAME_FILENAME
    LMG_TASK_MESSAGE_FILENAME
    LMG_ERROR_THEME
)

printf '#!/usr/bin/env bash\n'

for IMPORT in "${IMPORTS[@]}"; do
    printf "$IMPORT=\$$IMPORT "
done

printf '"%%s/lmg.sh" "$@"'